[package]
name = "tribune"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
devserver_lib = {version = "0.4.2", features = ["reload"]}
notify = { version = "6.1.1", features = ["serde"] }
pathdiff = "0.2.1"
